format = """
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status
$directory
[ec2 instance](bold fg:orange)$character"""

[directory]
truncate_to_repo = false
before_repo_root_style = 'bold cyan'
repo_root_style = 'bold green'
truncation_symbol = '../'
truncation_length = 0

[kubernetes]
disabled = false
format = '[$symbol\($namespace\)]($style) '
